config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :tasks
  resources :genres

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :task
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :genre
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def new
  end

  def create
  end

  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to genres_path
  end

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def show
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to genres_path
  end

  def index
    @tasks = Task.all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/genres/edit.html.erb
<h1>Genres#edit</h1>
<p>Find me in app/views/genres/edit.html.erb</p>

app/views/genres/index.html.erb
<h1>ジャンル新規投稿</h1>
<%= form_for(@genre) do |f| %>
<%= f.label :name, '名前' %>
<%= f.text_field :name %>
<%= f.submit '作成' %>
<% end %>

<h1>ジャンル一覧</h1>
<% @genres.each do |genre| %>
<p><%= genre.name %></p>
<%= link_to "タスクを追加する", new_task_path %>
<%= link_to "削除", genre_path(genre.id), method: :delete, data: {confirm: "このタスクを削除しますか？"} %>
<%= link_to "編集", edit_genre_path(genre.id) %>
<% end %>

app/views/genres/new.html.erb
<h1>ジャンル新規投稿</h1>
<%= form_for(@genre) do |f| %>
<%= f.label :name, '名前' %>
<%= f.text_field :name %>
<%= f.submit '作成' %>
<% end %>

app/views/genres/show.html.erb
<h1>Genres#show</h1>
<p>Find me in app/views/genres/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<p><%= link_to "タスクを作成する", new_task_path %></p>
<% @tasks.each do |task| %>
<%= task.name %>
<%= link_to "削除", task_path(task.id), method: :delete, data: {confirm: "タスクを削除しますか？"} %>
<% end %>

app/views/tasks/new.html.erb
<h1>新規タスク登録</h1>
<%= form_for(@task) do |f| %>
<%= f.label :name, '名前' %>
<%= f.text_field :name %>
<%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--" %>
<%= f.submit '作成' %>
<% end %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>